import math as m ddgggrrrrvveeeseeeeceeeeeeeeeeeeeeeeeeeeee
import numpy as npeeeeeeeeeeeee
import matplotlib.pyplot as plt 333333333333
import scipy.integrate as spi juthhhhhhhhhhhhhhhhhhhh3rdewwwcsxxxxxxxx
import scipy.optimize as spoggggggggghiiuuijthvhhhhhhhhhhhhtjgggggunnnnggggggghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhghgdvdvddvdvvddvdvcccxxxxxxxxxxwwwwaaa
import scipy.special as spsGGGGGGGGGGGGGGGGGHHHHHHHHHHHHHHHTTHHHHHHHTTTHTGGRRRRRRRBDSDGHEDWDWDWWDWWWDWDDWDWWDWWDWDWDDWggdffffffffffffffffffffffffffffffffffffffrfrffrffrffffffaaffffffffffffff33333ffffffffffffffffffefefefeef