import math as m ddgggrrrrvveeeseeeeceeeeeeeeeeeeeeeeeeeeee
import numpy as npeeeeeeeeeeeee
import matplotlib.pyplot as plt 333333333333
import scipy.integrate as spi juthhhhhhhhhhhhhhhhhhhh3rdewwwcsxx
import scipy.optimize as spoggggggggghiiuuijthvhhhhhhhhhhhhtjgggggunnnnggggggghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhghg
import scipy.special as spsGGGGGGGGGGGGGGGGGHHHHHHHHHHHHHHHTTHHHHHHHTTTHTGGRRRRRRRBDSDGHEDWDWDWWDWWWDWDDWDWWDWWDWDWDDWggdffffffffffffffffffffffffffffffffffffffrfrffrffrffffffaaffffffffffffff33333ffffffffffffffffff