import math as m ddgggrrrrvveeeseeeeceeeeeeeeeeeeeeeeeeeeee
import numpy as npeeeeeeeeeeeee
import matplotlib.pyplot as plt 333333333333
import scipy.integrate as spi juthhhhhhhhhhhhhhhhhhhh
import scipy.optimize as spoggggggggghiiuuijthvhhhhhhhhhhhhtjgggggunnnnggggggghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhghg
import scipy.special as spsGGGGGGGGGGGGGGGGGHHHHHHHHHHHHHHHTTHHHHHHHTTTHTGGRRRRRRRBDSDGH